/**
 * Seed Script — Multi-tenant demo data
 *
 * Creates:
 *   - 1 admin hospital  (City Medical Center)  + 15 patients
 *   - 4 regular hospitals                       + 8–12 patients each
 *   - All passwords: "Test@1234"
 *   - mustChangePassword: false (so you can login directly)
 *   - Each hospital gets a unique 6-digit authCode auto-generated by the model
 *   - Varied registration dates for patients
 *
 * Run:  node src/seed.js
 */

import mongoose from "mongoose";
import dotenv from "dotenv";
import path from "path";
import fs from "fs";

// Load env
const devEnvPath = path.resolve(process.cwd(), ".env.development");
if (fs.existsSync(devEnvPath)) dotenv.config({ path: devEnvPath });
else dotenv.config();

import Hospital from "./models/Hospital.js";
import Patient from "./models/Patient.js";
import Session from "./models/Session.js";
import AuditLog from "./models/AuditLog.js";
import { hashPassword } from "./utils/hash.js";
import logger from "./utils/logger.js";

const MONGO_URI = process.env.MONGODB_URI || "mongodb://localhost:27017/hospital-management";
const PASSWORD = "Test@1234";

// ─── Hospital data ───

const hospitals = [
  {
    hospitalName: "City Medical Center",
    email: "admin@citymedical.com",
    phone: "+919876543210",
    role: "admin",
    address: "42 MG Road",
    city: "Mumbai",
    state: "Maharashtra",
    zipCode: "400001",
    logoUrl: "https://ui-avatars.com/api/?name=City+Medical&background=1d4ed8&color=fff&size=150&bold=true&format=png",
  },
  {
    hospitalName: "Sunrise Health Clinic",
    email: "admin@sunrisehealth.in",
    phone: "+919876543211",
    role: "hospital",
    address: "15 Nehru Nagar",
    city: "Delhi",
    state: "Delhi",
    zipCode: "110001",
    logoUrl: "https://ui-avatars.com/api/?name=Sunrise+Health&background=059669&color=fff&size=150&bold=true&format=png",
  },
  {
    hospitalName: "LifeCare Hospital",
    email: "admin@lifecare.org",
    phone: "+919876543212",
    role: "hospital",
    address: "78 Park Street",
    city: "Kolkata",
    state: "West Bengal",
    zipCode: "700016",
    logoUrl: "https://ui-avatars.com/api/?name=LifeCare&background=dc2626&color=fff&size=150&bold=true&format=png",
  },
  {
    hospitalName: "Green Valley Medical",
    email: "admin@greenvalley.com",
    phone: "+919876543213",
    role: "hospital",
    address: "3 Residency Road",
    city: "Bangalore",
    state: "Karnataka",
    zipCode: "560025",
    logoUrl: "https://ui-avatars.com/api/?name=Green+Valley&background=7c3aed&color=fff&size=150&bold=true&format=png",
  },
  {
    hospitalName: "Apollo Care Institute",
    email: "admin@apollocare.in",
    phone: "+919876543214",
    role: "hospital",
    address: "101 Anna Salai",
    city: "Chennai",
    state: "Tamil Nadu",
    zipCode: "600002",
    logoUrl: "https://ui-avatars.com/api/?name=Apollo+Care&background=ea580c&color=fff&size=150&bold=true&format=png",
  },
];

// ─── Patient data pool ───

const firstNames = [
  "Aarav", "Vivaan", "Aditya", "Vihaan", "Arjun",
  "Reyansh", "Sai", "Arnav", "Dhruv", "Kabir",
  "Ananya", "Diya", "Myra", "Sara", "Aadhya",
  "Isha", "Kiara", "Riya", "Priya", "Neha",
  "Rohan", "Karan", "Raj", "Amit", "Suresh",
  "Meera", "Pooja", "Sneha", "Kavya", "Tanvi",
  "Vikram", "Nikhil", "Rahul", "Sanjay", "Deepak",
  "Lakshmi", "Radha", "Gita", "Suman", "Rekha",
];

const lastNames = [
  "Sharma", "Patel", "Singh", "Kumar", "Gupta",
  "Reddy", "Nair", "Joshi", "Mehta", "Shah",
  "Verma", "Iyer", "Rao", "Pillai", "Das",
  "Malhotra", "Chopra", "Banerjee", "Mukherjee", "Sinha",
];

function randomDate(start, end) {
  return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
}

function generatePatients(hospitalId, count, initials) {
  const patients = [];
  // Spread createdAt over last 7 days
  const now = new Date();
  const sevenDaysAgo = new Date(now);
  sevenDaysAgo.setDate(now.getDate() - 7);

  for (let i = 0; i < count; i++) {
    const first = firstNames[Math.floor(Math.random() * firstNames.length)];
    const last = lastNames[Math.floor(Math.random() * lastNames.length)];
    const createdAt = randomDate(sevenDaysAgo, now);

    patients.push({
      hospitalId,
      patientName: `${first} ${last}`,
      patientId: `${initials}-${String(i + 1).padStart(3, "0")}`,
      remarks: i % 3 === 0 ? "Regular checkup patient" : i % 5 === 0 ? "Follow-up required" : undefined,
      createdAt,
      updatedAt: createdAt,
    });
  }
  return patients;
}

// ─── Main ───

async function seed() {
  logger.info({ event: "seed_started" }, "=== Hospital Management — Seed Script ===");
  logger.info(
    { event: "seed_mode", mode: "non_destructive" },
    "[Seed] Non-destructive mode: existing hospitals/patients are left untouched."
  );

  if (process.env.NODE_ENV === "production") {
    logger.error({ event: "seed_refused_in_prod" }, "Refusing to run seed in production (NODE_ENV=production).");
    process.exit(1);
  }

  try {
    await mongoose.connect(MONGO_URI);
    logger.info(
      { event: "seed_db_connected", uri: MONGO_URI.replace(/:([^@]+)@/, ":****@") },
      "[DB] Connected"
    );

    // ── Hash password once ──
    const passwordHash = await hashPassword(PASSWORD);
    logger.info({ event: "seed_password_ready", password: PASSWORD }, `[Seed] Password for new accounts: ${PASSWORD}`);

    // ── Create hospitals (skip if already exists by email) ──
    const resolvedHospitals = [];
    const patientCounts = [2, 1, 2, 1, 2];
    const hospitalInitials = ["CMC", "SHC", "LCH", "GVM", "ACI"];

    for (let i = 0; i < hospitals.length; i++) {
      const h = hospitals[i];
      let hospital = await Hospital.findOne({ email: h.email });

      if (hospital) {
        const emoji = h.role === "admin" ? "(ADMIN)" : "       ";
        logger.info(
          { event: "seed_hospital_skipped", hospitalName: h.hospitalName, role: h.role },
          `  [Hospital] ${emoji} ${h.hospitalName} — already exists, skipped`
        );
      } else {
        hospital = await Hospital.create({
          ...h,
          passwordHash,
          isActive: true,
          mustChangePassword: false,
          failedLoginAttempts: 0,
          lockUntil: null,
          biometricKeys: [],
        });
        const emoji = h.role === "admin" ? "(ADMIN)" : "       ";
        logger.info(
          { event: "seed_hospital_created", hospitalName: h.hospitalName, role: h.role },
          `  [Hospital] ${emoji} ${h.hospitalName} — created`
        );
        logger.info(
          {
            event: "seed_hospital_credentials",
            email: h.email,
            phone: h.phone,
            authCode: hospital.authCode,
          },
          `             Login: ${h.email} | ${h.phone}  (AuthCode: ${hospital.authCode})`
        );
      }

      resolvedHospitals.push(hospital);
    }

    // ── Create patients (skip if patientId already exists for that hospital) ──
    let created = 0;
    let skipped = 0;

    for (let i = 0; i < resolvedHospitals.length; i++) {
      const hospital = resolvedHospitals[i];
      const count = patientCounts[i];
      const initials = hospitalInitials[i];
      const patients = generatePatients(hospital._id, count, initials);

      let hospitalCreated = 0;
      for (const p of patients) {
        const exists = await Patient.findOne({ hospitalId: hospital._id, patientId: p.patientId });
        if (exists) {
          skipped++;
        } else {
          await Patient.create(p);
          hospitalCreated++;
          created++;
        }
      }

      // Sync patientIdCounter only if new patients were added
      if (hospitalCreated > 0) {
        const total = await Patient.countDocuments({ hospitalId: hospital._id });
        await Hospital.updateOne({ _id: hospital._id }, { $set: { patientIdCounter: total } });
      }

      logger.info(
        {
          event: "seed_patients_batch",
          hospitalName: hospital.hospitalName,
          created: hospitalCreated,
          skipped: count - hospitalCreated,
        },
        `  [Patients] ${hospital.hospitalName}: ${hospitalCreated} added, ${count - hospitalCreated} skipped`
      );
    }

    logger.info(
      {
        event: "seed_complete",
        hospitalsProcessed: resolvedHospitals.length,
        patientsCreated: created,
        patientsSkipped: skipped,
        password: PASSWORD,
      },
      "=== Seed Complete ==="
    );
    logger.info(
      { event: "seed_login_hints" },
      "  Login as admin:    admin@citymedical.com   | +919876543210\n" +
        "  Login as hospital: admin@sunrisehealth.in   | +919876543211"
    );

  } catch (error) {
    logger.error({ event: "seed_failed", err: error }, "[Seed] Error");
  } finally {
    await mongoose.disconnect();
    logger.info({ event: "seed_db_disconnect" }, "[DB] Disconnected.");
    process.exit(0);
  }
}

seed();
