/**
 * Seed Script — Multi-tenant demo data
 *
 * Creates:
 *   - 1 admin hospital  (City Medical Center)  + 15 patients
 *   - 4 regular hospitals                       + 8–12 patients each
 *   - All passwords: "Test@1234"
 *   - mustChangePassword: false (so you can login directly)
 *   - Each hospital gets a unique 6-digit authCode auto-generated by the model
 *   - Varied registration dates for patients
 *
 * Run:  node src/seed.js
 */

import mongoose from "mongoose";
import dotenv from "dotenv";
import path from "path";
import fs from "fs";

// Load env
const devEnvPath = path.resolve(process.cwd(), ".env.development");
if (fs.existsSync(devEnvPath)) dotenv.config({ path: devEnvPath });
else dotenv.config();

import Hospital from "./models/Hospital.js";
import Patient from "./models/Patient.js";
import Session from "./models/Session.js";
import AuditLog from "./models/AuditLog.js";
import { hashPassword } from "./utils/hash.js";

const MONGO_URI = process.env.MONGODB_URI || "mongodb://localhost:27017/hospital-management";
const PASSWORD = "Test@1234";

// ─── Hospital data ───

const hospitals = [
  {
    hospitalName: "City Medical Center",
    email: "admin@citymedical.com",
    phone: "+919876543210",
    role: "admin",
    address: "42 MG Road",
    city: "Mumbai",
    state: "Maharashtra",
    zipCode: "400001",
    logoUrl: "https://ui-avatars.com/api/?name=City+Medical&background=1d4ed8&color=fff&size=150&bold=true&format=png",
  },
  {
    hospitalName: "Sunrise Health Clinic",
    email: "admin@sunrisehealth.in",
    phone: "+919876543211",
    role: "hospital",
    address: "15 Nehru Nagar",
    city: "Delhi",
    state: "Delhi",
    zipCode: "110001",
    logoUrl: "https://ui-avatars.com/api/?name=Sunrise+Health&background=059669&color=fff&size=150&bold=true&format=png",
  },
  {
    hospitalName: "LifeCare Hospital",
    email: "admin@lifecare.org",
    phone: "+919876543212",
    role: "hospital",
    address: "78 Park Street",
    city: "Kolkata",
    state: "West Bengal",
    zipCode: "700016",
    logoUrl: "https://ui-avatars.com/api/?name=LifeCare&background=dc2626&color=fff&size=150&bold=true&format=png",
  },
  {
    hospitalName: "Green Valley Medical",
    email: "admin@greenvalley.com",
    phone: "+919876543213",
    role: "hospital",
    address: "3 Residency Road",
    city: "Bangalore",
    state: "Karnataka",
    zipCode: "560025",
    logoUrl: "https://ui-avatars.com/api/?name=Green+Valley&background=7c3aed&color=fff&size=150&bold=true&format=png",
  },
  {
    hospitalName: "Apollo Care Institute",
    email: "admin@apollocare.in",
    phone: "+919876543214",
    role: "hospital",
    address: "101 Anna Salai",
    city: "Chennai",
    state: "Tamil Nadu",
    zipCode: "600002",
    logoUrl: "https://ui-avatars.com/api/?name=Apollo+Care&background=ea580c&color=fff&size=150&bold=true&format=png",
  },
];

// ─── Patient data pool ───

const firstNames = [
  "Aarav", "Vivaan", "Aditya", "Vihaan", "Arjun",
  "Reyansh", "Sai", "Arnav", "Dhruv", "Kabir",
  "Ananya", "Diya", "Myra", "Sara", "Aadhya",
  "Isha", "Kiara", "Riya", "Priya", "Neha",
  "Rohan", "Karan", "Raj", "Amit", "Suresh",
  "Meera", "Pooja", "Sneha", "Kavya", "Tanvi",
  "Vikram", "Nikhil", "Rahul", "Sanjay", "Deepak",
  "Lakshmi", "Radha", "Gita", "Suman", "Rekha",
];

const lastNames = [
  "Sharma", "Patel", "Singh", "Kumar", "Gupta",
  "Reddy", "Nair", "Joshi", "Mehta", "Shah",
  "Verma", "Iyer", "Rao", "Pillai", "Das",
  "Malhotra", "Chopra", "Banerjee", "Mukherjee", "Sinha",
];

function randomDate(start, end) {
  return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
}

function generatePatients(hospitalId, count, initials) {
  const patients = [];
  // Spread createdAt over last 2 years
  const now = new Date();
  const twoYearsAgo = new Date(now);
  twoYearsAgo.setFullYear(now.getFullYear() - 2);

  for (let i = 0; i < count; i++) {
    const first = firstNames[Math.floor(Math.random() * firstNames.length)];
    const last = lastNames[Math.floor(Math.random() * lastNames.length)];
    const createdAt = randomDate(twoYearsAgo, now);

    patients.push({
      hospitalId,
      patientName: `${first} ${last}`,
      patientId: `${initials}-${String(i + 1).padStart(3, "0")}`,
      remarks: i % 3 === 0 ? "Regular checkup patient" : i % 5 === 0 ? "Follow-up required" : undefined,
      createdAt,
      updatedAt: createdAt,
    });
  }
  return patients;
}

// ─── Main ───

async function seed() {
  console.log("\n=== Hospital Management — Seed Script ===\n");

  // ── SAFETY GATE ──────────────────────────────────────────────────────────
  // This script is DESTRUCTIVE — it wipes every hospital, patient, session
  // and audit-log document. We refuse to run unless:
  //   • NODE_ENV !== "production", AND
  //   • The caller passes either --force or sets SEED_CONFIRM=yes-wipe-everything
  //
  // A previous accidental run wiped live user data. Don't remove this gate
  // without adding a MongoDB snapshot / mongodump first.
  const forceFlag = process.argv.includes("--force") || process.env.SEED_CONFIRM === "yes-wipe-everything";
  if (process.env.NODE_ENV === "production") {
    console.error("✗ Refusing to run seed in production (NODE_ENV=production).");
    process.exit(1);
  }
  if (!forceFlag) {
    console.error("\n" + "━".repeat(72));
    console.error("⚠  DESTRUCTIVE OPERATION BLOCKED");
    console.error("━".repeat(72));
    console.error("This script will DELETE every document from:");
    console.error("    • hospitals");
    console.error("    • patients");
    console.error("    • sessions");
    console.error("    • auditlogs");
    console.error("...and replace them with demo data.");
    console.error("");
    console.error("If you really intend to wipe the database, re-run with one of:");
    console.error("    node src/seed.js --force");
    console.error("    SEED_CONFIRM=yes-wipe-everything node src/seed.js");
    console.error("");
    console.error("Before doing that, take a backup:");
    console.error("    mongodump --uri=\"$MONGODB_URI\" --out=./backup-$(date +%F)");
    console.error("━".repeat(72) + "\n");
    process.exit(1);
  }

  try {
    await mongoose.connect(MONGO_URI);
    console.log("[DB] Connected to", MONGO_URI.replace(/:([^@]+)@/, ":****@"));

    // ── Confirm destructive action ──
    console.log("[Seed] Dropping existing data (hospitals / patients / sessions / audit logs)...");
    await Promise.all([
      Hospital.deleteMany({}),
      Patient.deleteMany({}),
      Session.deleteMany({}),
      AuditLog.deleteMany({}),
    ]);
    console.log("[Seed] All collections cleared.\n");

    // ── Hash password once ──
    const passwordHash = await hashPassword(PASSWORD);
    console.log(`[Seed] Password for all accounts: ${PASSWORD}\n`);

    // ── Create hospitals ──
    const createdHospitals = [];
    const patientCounts = [2, 1, 2, 1, 2]; // patients per hospital
    const hospitalInitials = ["CMC", "SHC", "LCH", "GVM", "ACI"];

    for (let i = 0; i < hospitals.length; i++) {
      const h = hospitals[i];
      const hospital = await Hospital.create({
        ...h,
        passwordHash,
        isActive: true,
        mustChangePassword: false,
        failedLoginAttempts: 0,
        lockUntil: null,
        biometricKeys: [],
      });
      createdHospitals.push(hospital);

      const emoji = h.role === "admin" ? "(ADMIN)" : "       ";
      console.log(`  [Hospital] ${emoji} ${h.hospitalName}`);
      console.log(`             Login: ${h.email} | ${h.phone}  (AuthCode: ${hospital.authCode})`);
    }

    console.log("");

    // ── Create patients for each hospital ──
    let totalPatients = 0;
    for (let i = 0; i < createdHospitals.length; i++) {
      const hospital = createdHospitals[i];
      const count = patientCounts[i];
      const initials = hospitalInitials[i];
      const patients = generatePatients(hospital._id, count, initials);

      await Patient.insertMany(patients);
      totalPatients += count;

      // Keep hospital patientIdCounter in sync with seeded patient count
      await Hospital.updateOne({ _id: hospital._id }, { $set: { patientIdCounter: count } });

      console.log(`  [Patients] ${hospital.hospitalName}: ${count} patients (ID: ${initials}-XXX)`);
    }

    console.log(`\n=== Seed Complete ===`);
    console.log(`  Hospitals: ${createdHospitals.length}`);
    console.log(`  Patients:  ${totalPatients}`);
    console.log(`  Password:  ${PASSWORD} (all accounts)`);
    console.log(`  AuthCode:  Auto-generated per hospital (printed above — required as 2nd factor on login)`);
    console.log(`\n  Login as admin:    admin@citymedical.com   | +919876543210`);
    console.log(`  Login as hospital: admin@sunrisehealth.in   | +919876543211\n`);

  } catch (error) {
    console.error("[Seed] Error:", error);
  } finally {
    await mongoose.disconnect();
    console.log("[DB] Disconnected.");
    process.exit(0);
  }
}

seed();
