name: Auto Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            set -e

            echo "Starting deployment..."

            cd /root/Hospital-Management

            echo "Fetching latest code..."
            git fetch origin
            git reset --hard origin/main

            echo "Building and restarting containers..."
            docker compose up -d --build

            echo "Cleaning unused Docker images..."
            docker image prune -af

            echo "Deployment complete."

            echo "Container status:"
            docker ps
